"""
Mock wardrobe data — each item has a category, name, style tags, climate tags, and image URL.
Extend this list or swap for a database later.
"""

WARDROBE = [
    # ── TOPS ──────────────────────────────────────────────────────────────────
    {
        "id": "top_white_tee",
        "name": "Classic White T-Shirt",
        "category": "tops",
        "style": ["casual"],
        "climate": ["warm", "mild"],
        "color": "white",
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80",
    },
    {
        "id": "top_striped_tee",
        "name": "Striped Navy Tee",
        "category": "tops",
        "style": ["casual"],
        "climate": ["warm", "mild"],
        "color": "navy",
        "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&q=80",
    },
    {
        "id": "top_linen_shirt",
        "name": "Light Linen Shirt",
        "category": "tops",
        "style": ["casual", "smart-casual"],
        "climate": ["warm", "hot"],
        "color": "beige",
        "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80",
    },
    {
        "id": "top_blouse",
        "name": "Silk Blouse",
        "category": "tops",
        "style": ["smart-casual", "evening"],
        "climate": ["warm", "mild"],
        "color": "cream",
        "image": "https://images.unsplash.com/photo-1485462537746-965f33f53af3?w=400&q=80",
    },
    {
        "id": "top_thermal",
        "name": "Thermal Long-Sleeve",
        "category": "tops",
        "style": ["casual", "layering"],
        "climate": ["cold", "mild"],
        "color": "grey",
        "image": "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=400&q=80",
    },
    {
        "id": "top_knit_sweater",
        "name": "Knit Sweater",
        "category": "tops",
        "style": ["casual", "smart-casual"],
        "climate": ["cold", "mild"],
        "color": "camel",
        "image": "https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=400&q=80",
    },
    {
        "id": "top_evening_blouse",
        "name": "Satin Evening Top",
        "category": "tops",
        "style": ["evening"],
        "climate": ["warm", "mild", "cold"],
        "color": "black",
        "image": "https://images.unsplash.com/photo-1469334031218-e382a71b716b?w=400&q=80",
    },

    # ── BOTTOMS ───────────────────────────────────────────────────────────────
    {
        "id": "bottom_jeans",
        "name": "Dark Slim Jeans",
        "category": "bottoms",
        "style": ["casual", "smart-casual", "evening"],
        "climate": ["warm", "mild", "cold"],
        "color": "dark blue",
        "image": "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80",
    },
    {
        "id": "bottom_chinos",
        "name": "Beige Chinos",
        "category": "bottoms",
        "style": ["casual", "smart-casual"],
        "climate": ["warm", "mild"],
        "color": "beige",
        "image": "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80",
    },
    {
        "id": "bottom_shorts",
        "name": "Linen Shorts",
        "category": "bottoms",
        "style": ["casual"],
        "climate": ["hot", "warm"],
        "color": "sand",
        "image": "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=400&q=80",
    },
    {
        "id": "bottom_midi_skirt",
        "name": "Flowy Midi Skirt",
        "category": "bottoms",
        "style": ["casual", "smart-casual"],
        "climate": ["warm", "hot"],
        "color": "terracotta",
        "image": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=400&q=80",
    },
    {
        "id": "bottom_trousers",
        "name": "Wide-Leg Trousers",
        "category": "bottoms",
        "style": ["smart-casual", "evening"],
        "climate": ["mild", "cold"],
        "color": "black",
        "image": "https://images.unsplash.com/photo-1594938298603-c8148c4b4ae8?w=400&q=80",
    },

    # ── DRESSES ───────────────────────────────────────────────────────────────
    {
        "id": "dress_sundress",
        "name": "Floral Sundress",
        "category": "dresses",
        "style": ["casual"],
        "climate": ["hot", "warm"],
        "color": "floral",
        "image": "https://images.unsplash.com/photo-1572804013427-4d7ca7268217?w=400&q=80",
    },
    {
        "id": "dress_wrap",
        "name": "Wrap Dress",
        "category": "dresses",
        "style": ["casual", "smart-casual"],
        "climate": ["warm", "mild"],
        "color": "olive",
        "image": "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400&q=80",
    },
    {
        "id": "dress_evening",
        "name": "Little Black Dress",
        "category": "dresses",
        "style": ["evening"],
        "climate": ["warm", "mild", "cold"],
        "color": "black",
        "image": "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=400&q=80",
    },
    {
        "id": "dress_knit",
        "name": "Knit Midi Dress",
        "category": "dresses",
        "style": ["casual", "smart-casual"],
        "climate": ["cold", "mild"],
        "color": "burgundy",
        "image": "https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=400&q=80",
    },

    # ── JACKETS / OUTERWEAR ───────────────────────────────────────────────────
    {
        "id": "jacket_denim",
        "name": "Denim Jacket",
        "category": "jackets",
        "style": ["casual"],
        "climate": ["mild", "cold"],
        "color": "blue",
        "image": "https://images.unsplash.com/photo-1601333144130-8cbb312386b6?w=400&q=80",
    },
    {
        "id": "jacket_trench",
        "name": "Trench Coat",
        "category": "jackets",
        "style": ["smart-casual", "evening"],
        "climate": ["mild", "cold"],
        "color": "camel",
        "image": "https://images.unsplash.com/photo-1548126032-079a0fb0099d?w=400&q=80",
    },
    {
        "id": "jacket_puffer",
        "name": "Lightweight Puffer",
        "category": "jackets",
        "style": ["casual"],
        "climate": ["cold"],
        "color": "navy",
        "image": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400&q=80",
    },
    {
        "id": "jacket_blazer",
        "name": "Tailored Blazer",
        "category": "jackets",
        "style": ["smart-casual", "evening"],
        "climate": ["mild", "cold", "warm"],
        "color": "black",
        "image": "https://images.unsplash.com/photo-1617127365659-c47fa864d8bc?w=400&q=80",
    },
    {
        "id": "jacket_cardigan",
        "name": "Oversized Cardigan",
        "category": "jackets",
        "style": ["casual", "layering"],
        "climate": ["mild", "cold"],
        "color": "oatmeal",
        "image": "https://images.unsplash.com/photo-1604644401890-0bd678c83788?w=400&q=80",
    },
    {
        "id": "jacket_light_layer",
        "name": "Linen Overshirt",
        "category": "jackets",
        "style": ["casual", "layering"],
        "climate": ["warm", "mild"],
        "color": "sage",
        "image": "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80",
    },

    # ── SHOES ─────────────────────────────────────────────────────────────────
    {
        "id": "shoes_white_sneakers",
        "name": "White Sneakers",
        "category": "shoes",
        "style": ["casual"],
        "climate": ["warm", "mild", "hot"],
        "color": "white",
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
    },
    {
        "id": "shoes_sandals",
        "name": "Leather Sandals",
        "category": "shoes",
        "style": ["casual"],
        "climate": ["hot", "warm"],
        "color": "tan",
        "image": "https://images.unsplash.com/photo-1603487742131-4160ec999306?w=400&q=80",
    },
    {
        "id": "shoes_ankle_boots",
        "name": "Ankle Boots",
        "category": "shoes",
        "style": ["casual", "smart-casual", "evening"],
        "climate": ["mild", "cold"],
        "color": "brown",
        "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80",
    },
    {
        "id": "shoes_heels",
        "name": "Block Heels",
        "category": "shoes",
        "style": ["evening", "smart-casual"],
        "climate": ["warm", "mild", "cold"],
        "color": "nude",
        "image": "https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?w=400&q=80",
    },
    {
        "id": "shoes_loafers",
        "name": "Leather Loafers",
        "category": "shoes",
        "style": ["smart-casual", "casual"],
        "climate": ["mild", "warm", "cold"],
        "color": "black",
        "image": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=400&q=80",
    },
    {
        "id": "shoes_chunky_boots",
        "name": "Chunky Boots",
        "category": "shoes",
        "style": ["casual"],
        "climate": ["cold"],
        "color": "black",
        "image": "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=400&q=80",
    },
]
